# Generated by Django 5.2 on 2025-04-30 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contato',
            new_name='Contact',
        ),
    ]
